### ISSUE TITLE
.NETStandard NuGet version

### ISSUE THREAD

**Issue by KarlKl** [monemihir/LZMA-SDK#1]
Hello.
Is it possible to submit a .NetStandard v2.0 version to NuGet? Because it is only compiled with the normal Framework versions of .NET.
Regards,
Karl

**Comment by monemihir** [comment]
Hi,


You mean .Net Core 2.0 right?


Regards,

Mihir


________________________________

**Comment by monemihir** [comment]
A new version has been released which includes .NETStandard 2.0 assembly.
