### ISSUE TITLE
Provide released version 18.06

### ISSUE THREAD

**Issue by ite-jankl** [monemihir/LZMA-SDK#2]
The [LZMA SDK](https://www.7-zip.org/sdk.html) is available in version 18.06. This package at the moment provides 18.01.

**Comment by monemihir** [comment]
Yep, working on that release. Should be up soon.

**Comment by monemihir** [comment]
Apologies for the laaaaaaaattteeeeeeeeee reply but 18.06 was not released since there were no changes to the C# SDK from the author of the 7zip library/package.
