### ISSUE TITLE
Why LGPL?

### ISSUE THREAD

**Issue by bgrainger** [monemihir/LZMA-SDK#5]
Since all the source code was put into the public domain by Igor Pavlov (see https://www.7-zip.org/sdk.html), I'm curious why the LGPL license was chosen for this project.

While I think it would be technically possible to comply with the LGPL in commercial software (by using dynamic linking), any commercial user should get legal advice to make sure it is compliant. This extra burden on commercial users seems unnecessary for a library that consists almost entirely of public domain code.

Are you open to relicensing under a more permissive license, such as MIT or CC0 1.0 Universal?

**Comment by monemihir** [comment]
Hmm that's a valid point.

No worries licensing with MIT. Will do that and release soon.
