### ISSUE TITLE
Problem with installing Nuget in VS2019

### ISSUE THREAD

**Issue by JarekParal** [monemihir/LZMA-SDK#7]
I tried to install this NuGet package to my DLL project and I got this error message: `Could not install package 'LZMA-SDK 19.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I have VS 2019 v16.9.0 (.NET Framework 4.8.04084) on Windows 10 20H2 (19042.867).

My project use:
- Windows SDK Version: `10.0.18362.0`
- Platform Toolset: `v142`
- C++ Language Standard: `std:c++17`
- C Language Standard: `Legacy MSVC`

The project is part of a bigger solution where are also some C# project which uses this DLL project.

Do I have some problem with my configuration or is there some problem with this Nuget package?

Full log:
```
Attempting to gather dependency information for package 'LZMA-SDK.19.0.0' with respect to project 'IOL\Algorithm', targeting 'native,Version=v0.0'
Gathering dependency information took 1 ms
Attempting to resolve dependencies for package 'LZMA-SDK.19.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'LZMA-SDK.19.0.0'
Resolved actions to install package 'LZMA-SDK.19.0.0'
Install failed. Rolling back...
Package 'LZMA-SDK.19.0.0' does not exist in project 'Algorithm'
Package 'LZMA-SDK.19.0.0' does not exist in folder 'E:\sandbox\LX\iol-mentor-4\BackEnd\packages'
Executing nuget actions took 41 ms
Could not install package 'LZMA-SDK 19.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:00.1302250
========== Finished ==========
```

**Comment by monemihir** [comment]
Hey,

Thanks for checking out the package. This package only targets managed runtime languages like C# and VB.Net. It can't be imported or referenced for a C++ project directly through NuGet. The package only bundles the C# wrapper code for LZMA.

You can try to manually download the package and add a reference to the DLL though I'm not sure whether it would work.

Cheers,
Mihir
________________________________
From: Jaroslav Páral ***@***.***>
Sent: Monday, 29 March 2021 11:38 PM
To: monemihir/LZMA-SDK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [monemihir/LZMA-SDK] Problem with installing Nuget in VS2019 (#7)


I tried to install this NuGet package to my DLL project and I got this error message: Could not install package 'LZMA-SDK 19.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I have VS 2019 v16.9.0 (.NET Framework 4.8.04084) on Windows 10 20H2 (19042.867).

My project use:

  *   Windows SDK Version: 10.0.18362.0
  *   Platform Toolset: v142
  *   C++ Language Standard: std:c++17
  *   C Language Standard: Legacy MSVC

The project is part of a bigger solution where are also some C# project which uses this DLL project.

Do I have some problem with my configuration or is there some problem with this Nuget package?

Full log:

Attempting to gather dependency information for package 'LZMA-SDK.19.0.0' with respect to project 'IOL\Algorithm', targeting 'native,Version=v0.0'
Gathering dependency information took 1 ms
Attempting to resolve dependencies for package 'LZMA-SDK.19.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'LZMA-SDK.19.0.0'
Resolved actions to install package 'LZMA-SDK.19.0.0'
Install failed. Rolling back...
Package 'LZMA-SDK.19.0.0' does not exist in project 'Algorithm'
Package 'LZMA-SDK.19.0.0' does not exist in folder 'E:\sandbox\LX\iol-mentor-4\BackEnd\packages'
Executing nuget actions took 41 ms
Could not install package 'LZMA-SDK 19.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:00.1302250
========== Finished ==========

**Comment by JarekParal** [comment]
Hey @monemihir,

Thank you for your quick answer. I didn't know that there is C# wrapper for LZMA,

It would be good to have this information in README. Just like:
"This NuGet package is C# wrapper for LZMA SDK."

Cheers,

Jarek

**Comment by monemihir** [comment]
Thanks for the suggestion. I've updated the readme for the latest version.
